pipeline:
  build:
    image: mhart/alpine-node:6
    cache:
      - node_modules
    commands:
      - npm install 
    environment:
      - PORT=6969
      - IP=localhost
      - NODE_ENV=development
